apiVersion: apps/v1
kind : Deployment
metadata:
  name: platform-depl
spec:
  replicas: 1 # it will make sure atleast one replica of container is always running even if we delete it will recreate
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: sudhanshudocker1195/platformservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80